### ISSUE TITLE
Docs v1 Update Checklist R Basics: Visualize

### ISSUE THREAD

**Issue by rosemm** [arcus/education_modules#387]
# Module Update Checklist
----
Name of Module: R Basics: Visualizing Data With ggplot2
PR for module update: #389 

This is the checklist for bringing a module up to date with the [latest major version of docs.md: v1](https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/ddc7d4a1a8659723c3f0db0a87fcc3b26a0ae071/docs.md#1) 
Note that this link points to a specific commit and is therefore frozen in time. 
If you want to update this checklist after pushing new changes to docs.md, be sure to update this link as well.

## Summary of changes

The biggest changes to docs for this version are extensive updates to the required front matter, including lots of new fields, and the introduction of shared macros to replace standardized sections.

The following sections provide a complete (hopefully!) list of potential changes to modules needed to bring them up to date with the new version of docs.md. 

## Front matter

Make sure the front matter includes all required fields from the new templates. Some of these are new fields and some are not.

TIP: You can also use the "Your front matter checklist" section of docs.md to get a customized list of the required front matter for a given module. 

* [x] For all modules
    - [x] author
    - [x] email
    - [x] version
    - [x] current\_version\_description
    - [x] module_type
    - [x] module\_template\_version (should this change to docs_version?)
    - [x] language
    - [x] narrator
    - [x] mode: Textbook
    - [x] title
    - [x] comment
    - [x] long_description
    - [x] estimated\_time\_in\_minutes
    - [x] pre_reqs 
    - [x] learning_objectives
    - [x] good\_first\_module
    - [x] sets\_you\_up\_for
    - [x] depends\_on\_knowledge\_available\_in
    - [x] version_history
    - [x] import: https://raw.githubusercontent.com/arcus/education_modules/main/_module_templates/macros.md

* [x] If the learner will need to code to meet the learning objectives, the following are required:

    - [x] coding_required: true
    - [x] coding_level
    - [x] coding_language

* [x] For modules using interactive R code (binder), the following are required:

    - [x] r_file
    - [x] coding_level
    - [x] coding_language
    - [x] import: https://raw.githubusercontent.com/arcus/education_modules/main/_module_templates/macros_r.md
    
* [ N/A ] For modules using interactive Python code (sagemath), the following are required:

    - [ N/A ] coding_level
    - [ N/A ] coding_language
    - [ N/A ] import: https://raw.githubusercontent.com/arcus/education_modules/main/_module_templates/macros_python.md

* [ N/A ] For modules using interactive SQL (AlaSQL), the following are required:

    - [ N/A ] coding_level
    - [ N/A ] coding_language
    - [ N/A ] import: https://raw.githubusercontent.com/arcus/education_modules/main/_module_templates/macros_sql.md
    - [ N/A ] import statements for any SQL tables needed

* [x] For modules about a particular kind of data, or teaching a particular data task/skill:

    - [ N/A ] data_domain
    - [x] data_task

* [x] For modules that are part of a sequence:

    - [x] sequence_name
    - [x] previous\_sequential\_module (only for modules that are not first in their sequence)

* [ N/A ] For modules that are parallel to another module:

    - [ N/A ] is\_parallel\_to

* [ N/A ] For wrapper modules:

    - [ N/A ] resource1_name
    - [ N/A ] resource1\_description
    - [ N/A ] resource1\_wellvetted
    - [ N/A ] resource1\_wellvetted\_text
    - [ N/A ] resource1\_maintained
    - [ N/A ] resource1\_maintained\_text
    - [ N/A ] resource1\_stablesupport
    - [ N/A ] resource1\_stablesupport\_text
    - [ N/A ] resource1\_a11y\_issues
    - [ N/A ] for wrapper modules with a second external resource, include all of the above for resource2 as well
    - [ N/A ] for wrapper modules with a third external resource, include all of the above for resource3 as well
    - [ N/A ] import: https://raw.githubusercontent.com/arcus/education_modules/main/_module_templates/macros_wrapper.md

The following should **NOT** be included in module front matter: 

- [x] REMOVED: any macros defined in the shared macro files
- [x] REMOVED: `link:  https://chop-dbhi-arcus-education-website-assets.s3.amazonaws.com/css/styles.css`
- [x] REMOVED: `script: https://kit.fontawesome.com/83b2343bd4.js`
- [x] REMOVED: `script:  https://code.jquery.com/jquery-3.6.0.slim.min.js`

## Macros

* [x] For all modules:
    - [x] Overview is created with the macro, not written
    - [x] Feedback is created with the macro, not written

* [x] For modules with interactive R, Python, or SQL:
    - [x] Lesson Preparation is created with the relevant macro, not written

* [ N/A ] For wrapper modules:
    - [ N/A ] Lesson Preparation is created with the relevant macro, not written
    - [ N/A ] There is a `print_resource` macro for each external resource just after the `lesson_prep_wrapper` macro

## Other changes

* [x] Avoid linking to our own modules in the Additional Resources section at the end of each module
* [x] Check that highlight boxes use the updated style

## Final check

These updates should not change the rendered module much, for the most part. 
To check, pull up the rendered version from before the update and your updated version and look for missing/changed/added content, or anything that's not rendering properly. 
For conveience, paste the liascript links here:

- Original: https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/dd92856bddc5de758ca19c53e94b181877f20143/r_basics_visualize_data/r_basics_visualize_data.md#1
- Update: https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/f3277e367ceb574b6016f66e2a1ea49650774c2f/r_basics_visualize_data/r_basics_visualize_data.md#1

When you're ready to finalize the updated module, do the following in the module front matter:

* [x] Increment `version` for the module. If no meaningful changes were made to the content of the module as it renders for learners, this is a revision. If there were updates to the module content (e.g. in the Additional Resources section), then it's a minor update.
* [x] Update `docs_version`
