### ISSUE TITLE
Improve checklist issue template for updating modules

### ISSUE THREAD

**Issue by rosemm** [arcus/education_modules#388]
- [x] link to docs [your front matter checklist](https://liascript.github.io/course/?https://raw.githubusercontent.com/arcus/education_modules/main/docs.md#8) for the front matter instead of replicating list in issue.
- [x] fix "module_template_version", should be "docs_version"
- [ ] add editor role?
- [x] remove extra checkboxes for "section headers"
- [x] put v1 in the issue name
- [x]  add instructions about updating version_history along with incrementing version?

**Comment by rosemm** [comment]
Not adding editor role at this time; that's a larger discussion for us to have.
